### ISSUE TITLE
WolvenKit.exe Not Running

### ISSUE THREAD

**Issue by rexxgta** [WolvenKit/WolvenKit-nightly-releases#1]
Double clicking on the WolvenKit.exe loads up the splash screen, however it does not load. Have also tried executing via cmd and it does the same. RedModding folder has also been deleted from the appdata folder, issue continued.

**Comment by rfuzzo** [comment]
yes correct, it's a bug with this version and will be fixed tomorrow. Sorry about the inconvenience.
